#! /bin/bash
# cálculo de fatorial -> 5! = 5.4.3.2.1 = 120

clear
echo "Fatorial"
echo ""
echo "Digite um número para calcular o fatorial = "
read num
fat=1
conta=2

while [ $conta -le $num ]
do
	((fat = $fat * $conta))
	((conta = $conta + 1))	
done

echo "Fatorial de $num = " "$fat"