#!/bin/bash
clear
echo "Digite primeiro número: "
read num1;
echo "Digite segundo  número: "
read num2;
echo "Digite a operação (1 = soma, 2 = subtração, 3 = divisão, 4 = multiplicação)"
read op;

case "$op" in
"1")
	res=$(("$num1"+"$num2"))
	echo "$num1 + $num2 = $res"
	;;
"2")
	res=$(("$num1"-"$num2"))
	echo "$num1 - $num2 = $res"
	;;
"3")
	if [ "$op" -eq 3 ] && [ "$num2" -eq 0 ]
	then
		echo "Impossível dividir por zero"	
	else
		res=$(("$num1"/"$num2"))
		echo "$num1 / $num2 = $res"
	fi
	;;
"4")
	res=$(("$num1"*"$num2"))
	echo "$num1 * $num2 = $res"
	;;
*)
	echo "Opção incorreta"
	;;
esac